; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-trgb]
platform = espressif32@6.8.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_port = COM5
monitor_speed = 460800
lib_extra_dirs = lib
board_build.cpu = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.filesystem_size = 2097152 ; (2MB in bytes)
monitor_filters = esp32_exception_decoder

build_flags = 
  
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1    ;https://community.platformio.org/t/enabling-usb-cdc-on-boot-on-esp32-c3-devkit/33346
	-DBOARD_HAS_PSRAM 
	-mfix-esp32-psram-cache-issue
  -DUSER_SETUP_LOADED=1
	-DLV_CONF_INCLUDE_SIMPLE
	-DNO_TX_TIMEOUT
  -DUSER_SETUP_LOADED=1
  ; These flags tell TFT_eSPI to let the board lib handle the settings
  -DILI9488_DRIVER=0 
  -DDISABLE_ALL_LIBRARY_WARNINGS
  -Ilib/TFT_eSPI/
	-DLV_FONT_MONTSERRAT_36=1
  -DLV_FONT_MONTSERRAT_48=1


lib_deps =
  h2zero/NimBLE-Arduino
  bodmer/TFT_eSPI
  IanH/TRGBArduinoSupport ;https://registry.platformio.org/libraries/ianh/TRGBArduinoSupport
  lvgl/lvgl @ 8.3.11
  PowerBroker2/ELMduino
  ;https://github.com/vdvornichenko/obd-ble-serial
  ;https://forum.arduino.cc/t/esp32-with-elm327/1315461

