// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: TEM V2

#include "../ui.h"


// IMAGE DATA: assets/Screen sc9.png
lv_img_dsc_t ui_img_screen_sc9_png = {
    .header.always_zero = 0,
    .header.w = 480,
    .header.h = 480,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_screen_sc9_png_load()
{
    ui_img_screen_sc9_png.data = UI_LOAD_IMAGE("S:assets/ui_img_screen_sc9_png.bin", 691200);
    ui_img_screen_sc9_png.data_size = 691200;
}
