// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: TEM V2

#ifndef _TEM_V2_UI_H
#define _TEM_V2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#include "ui_img_manager.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * GaugeSweep_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
extern lv_img_dsc_t ui_img_screen_bg_png;   // assets/Screen bg.png
void ui_img_screen_bg_png_load();
extern lv_img_dsc_t ui_img_screen_sc1_png;   // assets/Screen sc1.png
void ui_img_screen_sc1_png_load();
extern lv_img_dsc_t ui_img_screen_sc2_png;   // assets/Screen sc2.png
void ui_img_screen_sc2_png_load();
extern lv_img_dsc_t ui_img_screen_sc3_png;   // assets/Screen sc3.png
void ui_img_screen_sc3_png_load();
extern lv_img_dsc_t ui_img_screen_sc4_png;   // assets/Screen sc4.png
void ui_img_screen_sc4_png_load();
extern lv_img_dsc_t ui_img_screen_sc5_png;   // assets/Screen sc5.png
void ui_img_screen_sc5_png_load();
extern lv_img_dsc_t ui_img_screen_sc6_png;   // assets/Screen sc6.png
void ui_img_screen_sc6_png_load();
extern lv_img_dsc_t ui_img_screen_sc7_png;   // assets/Screen sc7.png
void ui_img_screen_sc7_png_load();
extern lv_img_dsc_t ui_img_screen_sc8_png;   // assets/Screen sc8.png
void ui_img_screen_sc8_png_load();
extern lv_img_dsc_t ui_img_screen_sc9_png;   // assets/Screen sc9.png
void ui_img_screen_sc9_png_load();
extern lv_img_dsc_t ui_img_screen_sc10_png;   // assets/Screen sc10.png
void ui_img_screen_sc10_png_load();
extern lv_img_dsc_t ui_img_screen_sc11_png;   // assets/Screen sc11.png
void ui_img_screen_sc11_png_load();
extern lv_img_dsc_t ui_img_screen_sc12_png;   // assets/Screen sc12.png
void ui_img_screen_sc12_png_load();
extern lv_img_dsc_t ui_img_screen_sc13_png;   // assets/Screen sc13.png
void ui_img_screen_sc13_png_load();
extern lv_img_dsc_t ui_img_screen_sc14_png;   // assets/Screen sc14.png
void ui_img_screen_sc14_png_load();
extern lv_img_dsc_t ui_img_screen_sc15_png;   // assets/Screen sc15.png
void ui_img_screen_sc15_png_load();

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
