// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: TEM V2

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_MainGaugeEmpty;
extern lv_obj_t * ui_Center_Label;
extern lv_obj_t * ui_Main_Gauge;
extern lv_obj_t * ui_Main_Gauge_Orange;
extern lv_obj_t * ui_Main_Gauge_Red;
extern lv_obj_t * ui_Main_Gauge_Negative;
extern lv_obj_t * ui_Tick_Marks;
extern lv_obj_t * ui_Secondary_Label;
extern lv_obj_t * ui_Secondary_Gauge;
extern lv_obj_t * ui_Negative_Label;
extern lv_obj_t * ui_Zero_Label;
extern lv_obj_t * ui_Max_Label;
extern lv_obj_t * ui_Red_Label;
extern lv_obj_t * ui_Function_Label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

